### PR TITLE
Revert "Proper initialization of the bridge pot account balances in genesis (#698)"

### PR DESCRIPTION
**Pull request by dmitrylavrenov**
This reverts commit https://github.com/humanode-network/humanode/pull/698.

The new one genesis bridges logic has been implemented at https://github.com/humanode-network/humanode/pull/716 and https://github.com/humanode-network/humanode/pull/719

### CODE REVIEW

**Comment by MOZGIII** [comment]
Not sure if a simple rollback is the correct approach here. It will most definitely have conflicts with #719. Maybe doing it manually would be more accurate.

**Comment by dmitrylavrenov** [comment]
> Not sure if a simple rollback is the correct approach here. It will most definitely have conflicts with #719. Maybe doing it manually would be more accurate.

It looks working as I've checked tests and build locally. All that I need now is fixing feature snapshot.

**Comment by MOZGIII** [comment]
Did you test on top of https://github.com/humanode-network/humanode/pull/719?

**Comment by dmitrylavrenov** [comment]
> Did you test on top of #719?
> On master without #719 it will merge without issues for obvious reasons.

The conflicts have been resolved.

**Review by MOZGIII — APPROVED** [review]

**Pull request merged**
