### PR TITLE
Set EVM currency existential deposit to 1

### LINKED ISSUE #781: Set EVM currency existenial deposit to 1

### PR DESCRIPTION
**Pull request by MOZGIII**
Closes #781.

- #781

Waits for #785 to land before merging.

### CODE REVIEW

**Comment by dmitrylavrenov** [comment]
Should we research and properly run migrations at this PR?

**Comment by MOZGIII** [comment]
> Should we research and properly run migrations at this PR?

Let's discuss

**Comment by dmitrylavrenov** [comment]
Spent time on research in a little:
- `Balances` and `EvmBalances` don't have some migration logic. Anyway, in case new ED is less than an older one then it doesn't influence on accounts creation/deletion during runtime upgrade
- Checked that we should update bridges initializer version - https://github.com/humanode-network/humanode/commit/53f319e7680bc065ee4dfbf924e6092a6211477f

**Comment by MOZGIII** [comment]
So, this should just work, right? We'll have to test extensively through try-runtime and on the internal testing stages before we ship even to testnet.

**Comment by dmitrylavrenov** [comment]
> So, this should just work, right? I don't see why not... However, we'll have to test extensively through try-runtime and on the internal testing stages before we ship even to testnet.

Yes, this should. Right, agree with the way of testing.

**Review by dmitrylavrenov — APPROVED** [review]

**Pull request merged**
