### PR TITLE
Add typos check to CI

### PR DESCRIPTION
**Pull request by MOZGIII**

### CODE REVIEW

**Review by dmitrylavrenov — APPROVED** [review]

**Comment by MOZGIII** [comment]
@dmitrylavrenov why do you approve? It doesn't work

**Comment by dmitrylavrenov** [comment]
> @dmitrylavrenov why do you approve? It doesn't work

You asked and in the moment of my  reviewing checks have been in progress. I've got the logic of code changes and decided to approve without waiting CI progress.

**Comment by MOZGIII** [comment]
Well, now it works.

I've also added https://github.com/humanode-network/humanode/pull/1042.

Let's try to fix the typos. We can create a PR with all the non-breaking changes, and for the (hopefully few) breaking changes we should have a discussion.

Would you like to address this @dmitrylavrenov?

**Comment by MOZGIII** [comment]
Nvm, I'll take care of the fixes

**Pull request merged**
